version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  producer_order:
    build:
      context: ./producer_order
      dockerfile: Dockerfile
    container_name: producer_order
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      PYTHONUNBUFFERED: 1
    depends_on:
      - kafka
    ports:
      - "5001:5000"

  inventory_consumer:
    build:
      context: ./inventory_consumer
      dockerfile: Dockerfile
    container_name: inventory_consumer
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      PYTHONUNBUFFERED: 1
    depends_on:
      - kafka
    ports:
      - "5002:5000"

  analytics_consumer:
    build:
      context: ./analytics_consumer
      dockerfile: Dockerfile
    container_name: analytics_consumer
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      PYTHONUNBUFFERED: 1
    depends_on:
      - kafka
    ports:
      - "5003:5000"

  tests:
    build:
      context: ./tests
      dockerfile: Dockerfile
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      PRODUCER_URL: http://producer_order:5000
      PYTHONUNBUFFERED: 1
    depends_on:
      - kafka
      - producer_order
      - inventory_consumer
      - analytics_consumer
